# Generated by Django 4.0.6 on 2022-07-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_tasktable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
