# Generated by Django 4.0.6 on 2022-07-10 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_tasktable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='mtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
